In [2]:
import torch
import numpy as np

In [2]:
pip install torch

Note: you may need to restart the kernel to use updated packages.


In [6]:
# Construct a tensor from an array
array = [[1,2],[3,4],[5,6]]
tensor0 = torch.tensor(array)
print(tensor0)
print(type(tensor0))
print(tensor0.dtype)
print(tensor0.shape)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
<class 'torch.Tensor'>
torch.int64
torch.Size([3, 2])


In [8]:
# Construct a tensor from a numpy array
np_array = np.array([[1,2],[3,4],[5,6]])
tensor1 = torch.tensor(np_array)
print(tensor1)
print(type(tensor1))
print(tensor1.dtype)
print(tensor1.shape)

tensor([[1, 2],
        [3, 4],
        [5, 6]], dtype=torch.int32)
<class 'torch.Tensor'>
torch.int32
torch.Size([3, 2])


# Methods 

#SLICING

In [9]:
tensorA = torch.tensor([[1,2,3],[4,5,6]])
tensorB = torch.tensor([[7,8,9],[4,6,8]])

In [12]:
print(tensorA[:2])
print(tensorA[:, :2])

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2],
        [4, 5]])


#Concatenation

In [15]:
print("verticall concatenate tensorA and tensorB")
conc_v = torch.cat([tensorA, tensorB])
print(conc_v)
print("Horizontal concatination of tensorA and TensorB")
conc_h = torch.cat([tensorA, tensorB],dim = 1)
print(conc_h)

verticall concatenate tensorA and tensorB
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [4, 6, 8]])
Horizontal concatination of tensorA and TensorB
tensor([[1, 2, 3, 7, 8, 9],
        [4, 5, 6, 4, 6, 8]])
